title: Utilities/Schema
fields:
  -
    handle: schema_custom
    field:
      theme: material
      mode: htmlmixed
      mode_selectable: true
      indent_type: spaces
      indent_size: 4
      key_map: default
      line_numbers: true
      line_wrapping: true
      antlers: false
      type: code
      display: 'Custom Schema'
      icon: code
      instructions: 'Custom [Schema.org](https://schema.org) data in JSON-LD encoding.'
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
